### ISSUE TITLE
How would you go about using django ORM and django-generate-series to get 1 table with 1 item per (date, id) combination ? 

### ISSUE THREAD

**Issue by lionelwust** [OmenApps/django-generate-series#17]
Hello !

Let's say I have a table on one side and a date sequence on the other. I don't know how to generate a table containing each (date, item_id) combination, in 1 SQL query and using Django ORM.

I would like to be able to do that using Django ORM because I have a lot of post processing after that, i.e. annotations and aggregations.

I found a very similar question with a pure SQL answer:
[https://dba.stackexchange.com/questions/133406/postgresql-generate-a-series-of-dates-for-each-group-in-a-table](https://dba.stackexchange.com/questions/133406/postgresql-generate-a-series-of-dates-for-each-group-in-a-table)

**Comment by jacklinke** [comment]
@lionelwust I am very sorry to have missed your question for so many months. I know it's probably far too late to be useful to your project, but I've updated the package to product the cartesian product of an input QuerySet or iterable.

Fixed in d404ebf3e2e026135a4052576d39673a38e63343

Thank you for pointing out a useful feature.

Released as a beta while I clean up the code and tests a bit more.

**Comment by lionelwust** [comment]
That's nice, will try to use it !

Have a good day, Lionel

**Comment by lionelwust** [comment]
Hello @jacklinke,
I hope you are doing well. Are you planning to release https://github.com/OmenApps/django-generate-series/releases/tag/1.0.0b1 on PyPI ? It would be great to have easy access to the new features and fixes you developped.
Have a great day,
Lionel
